### PR TITLE
5) Jako zalogowany użytkownik mogę wyświetlić listę rowerów na wybranej stacji

### PR DESCRIPTION
**Pull request by MSterczewski**
Testy grupy L

### CODE REVIEW

**Review by piotrduperas — CHANGES_REQUESTED** [review]
According to our yesterday's discussion, tests should not assume existance of entities with particular IDs (there is a test of /stations/1/bikes). Moreover, tests should register a new user, they should not expect token to be provided.

**Comment by MSterczewski** [comment]
@piotrduperas  Fixed dependency on ID. However token is being set as environmental variable in postman during registration. This token is then used as authentication and functionality does not require additional logging in

**Comment by piotrduperas** [comment]
@MSterczewski We assumed that we should register user in every test. Token as env might be not a good idea if some team has tokens that expire. They would need to obtain token before testing which seems quite cumbersome.

**Comment by MSterczewski** [comment]
@piotrduperas  The collection that is submitted by our team contains of 3 tests. First one is registering a user and saving the received token to the variable. Second and third use that token as their authentication. Running the collection will in fact register a user and keep the token assimilated to that user in a variable. In order to run the tests no team will need to obtain any tokens.

**Review by smogork — APPROVED** [review]
Poprawiłem strukturę folderów i sprawdziłem test. wszystko przechodzi przy podstawowej konfiguracji bazy.

**Pull request merged**
